name: Spring-Docker CI/CD

env:
  IMAGE_NAME: remayke/learning
  IMAGE_TAG: github
  DOCKER_USERNAME: remayke

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:
  

  test-build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
        
    - run: ./mvnw clean package

    - uses: actions/upload-artifact@master
      with:
        name: app
        path: ./target/*.jar
        


  docker:
    needs: test-build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: app
        path: ./target/
        
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: remayke
        password: ${{ secrets.DOCKER_PASS }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
        
        
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: remove ssh command using pass
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        script: export PATH=$PATH:/usr/bin/docker &&
                echo ${{secrets.DOCKER_PASS}} | docker login --username "${{env.DOCKER_USERNAME}}" --password-stdin &&
                docker ps -aq | xargs --no-run-if-empty docker stop &&
                docker ps -aq | xargs --no-run-if-empty docker rm &&
                docker images -aq | xargs --no-run-if-empty docker rmi &&
                docker run -d -p 80:8080 ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}